version: '2.1'

services:
  logs:
    entrypoint:
    - '/bin/logspout'
    - '${LOGSPOUT_ENDPOINT}'

  nginx:
    build: nginx/prod
    volumes:
    - media:/media:ro
    restart: always
    ports:
    - 443:443
    depends_on:
    - web
