FROM datadog/docker-dd-agent:latest-alpine
ADD conf.d/redisdb.yaml /etc/dd-agent/conf.d/redisdb.yaml
ADD conf.d/postgres.yaml /etc/dd-agent/conf.d/postgres.yaml
ADD conf.d/docker_daemon.yaml /etc/dd-agent/conf.d/docker_daemon.yaml
